apiVersion: v1
kind: Service
metadata:
  name: hiveserver2
  namespace: bd-bd-gr-02
  labels:
    app: hiveserver2
spec:
  ports:
    - name: thrift
      port: 10000
      targetPort: 10000
      protocol: TCP
    - name: http
      port: 10002
      targetPort: 10002
      protocol: TCP
  selector:
    app: hiveserver2
