apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-warehouse-pvc
  namespace: bd-bd-gr-02
  labels:
    app: hiveserver2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
