apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: bd-bd-gr-02
  labels:
    app: hive-metastore
spec:
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP
  selector:
    app: hive-metastore
