apiVersion: v1
kind: Pod
metadata:
  name: volume-cleaner-root
  namespace: bd-bd-gr-02
spec:
  containers:
    - name: cleaner
      image: bitnami/spark:3.5.2-debian-12-r1
      securityContext:
        runAsUser: 0
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: spark-streaming-pvc