apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  namespace: bd-bd-gr-02
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  serviceName: "datanode"
  replicas: 3
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: datanode
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9864
          env:
            - name: SERVICE_PRECONDITION
              value: "namenode:9870"
          envFrom:
            - configMapRef:
                name: hadoop-config
          volumeMounts:
            - name: hadoop-datanode-storage
              mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
    - metadata:
        name: hadoop-datanode-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
