apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: bd-bd-gr-02
spec:
  selector:
    app: datanode
  ports:
    - name: datanode
      protocol: TCP
      port: 9864
      targetPort: 9864
