apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: bd-bd-gr-02
spec:
  selector:
    app: namenode
  ports:
    - name: web
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: rpc
      protocol: TCP
      port: 9000
      targetPort: 9000
