apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-schema-registry-config
  namespace: bd-bd-gr-02
data:
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
