apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  namespace: bd-bd-gr-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_PROCESS_ROLES
              value: broker
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-controller-0.kafka-controller-headless.bd-bd-gr-02.svc.cluster.local:9093,1@kafka-controller-1.kafka-controller-headless.bd-bd-gr-02.svc.cluster.local:9093,2@kafka-controller-2.kafka-controller-headless.bd-bd-gr-02.svc.cluster.local:9093"
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker.bd-bd-gr-02.svc.cluster.local:9092
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CFG_LOG_DIRS
              value: /bitnami/kafka/data
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
