apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry
  namespace: bd-bd-gr-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
        - name: kafka-schema-registry
          image: confluentinc/cp-schema-registry:7.3.1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: kafka-schema-registry-config
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
