apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
  namespace: bd-bd-gr-02
spec:
  selector:
    app: kafka-schema-registry
  ports:
    - name: web
      protocol: TCP
      port: 8081
      targetPort: 8081
