apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: bd-bd-gr-02
spec:
  type: NodePort
  selector:
    app: kafka-broker
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: 30092
