apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: bd-bd-gr-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/console:v2.7.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: redpanda-config
