apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-config
  namespace: bd-bd-gr-02
data:
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_SCHEMAREGISTRY_ENABLED: "true"
  KAFKA_SCHEMAREGISTRY_URLS: "http://kafka-schema-registry:8081"
  CONNECT_ENABLED: "true"
  CONNECT_CLUSTERS_NAME: "Connectors"
  CONNECT_CLUSTERS_URL: "http://kafka-connect:8083"
